### ISSUE TITLE
You can add ひらがな,カタカナ, Clear Romaji  Field.

### ISSUE THREAD

**Issue by stone89son** [nobuf/list-of-cities-in-japan#4]
The first, Thank for sharing data. 
You can add ひらがな ,カタカナ, Clear Romaji [Chūō-> example "Chuo-ku" ] name to list?
I and everyone use to search field .

**Comment by nobuf** [comment]
Since the official spreadsheet provided by the government includes カナ, it is possible to add ひらがな as well. As for the special characters like ā, ī, ū, ē, ō, we can convert them to ascii. (a, i, u, e, o)

I think it'd be better to add another file "build/cities_in_japan_2019_with_kana.csv" with additional columns, rather than adding those to the current build/cities_in_japan_2019.csv.

Your pull request is welcomed, but I'm happy to implement it sometime soon :)

**Comment by stone89son** [comment]
Yes. Thank @nobuf for reply and listening.
